name: 打包Nextjs项目

on: push

jobs:
  #  job1:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - run: pwd
  #      - run: ls
  #  job2:
  #    runs-on: windows-latest
  #    steps:
  #      - run: node --version

  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      packages: write

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 检出代码
        uses: ls -la # 验证构建上下文

      - name: 登陆DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: 构建并推送到Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: . # 明确指定构建上下文
          push: true
          tags: |
            taylorbeckent/github-actions:latest
            taylorbeckent/github-actions:${{ github.sha }}

#      - name: 安装依赖 和 项目打包
#        run: |
#          npm install
#          npm run build
#
#      - name: 验证构建结果
#        run: ls -lah dist
#
#      - name: 项目部署
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          branch: gh-pages
#          folder: dist
#          clear: true
